name: Update Translation Source

on:
  workflow_dispatch:
  schedule:
    # runs at the start of each month (UTC)
    - cron: '0 0 1 * *'

jobs:
  translations:
    # Do not run the scheduled workflow on forks, and ensure the action runs only from master branch
    if: (github.event != 'schedule' || github.repository_owner == 'Cockatrice') && github.ref_name == 'master'

    name: Update source strings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install lupdate
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qttools5-dev-tools

      - name: Update Cockatrice translation source
        id: cockatrice
        shell: bash
        run: |
          shopt -s globstar # globstar is needed for recursive **
          lupdate -version
          echo "reading the following source files:"
          # note: there are three strings to translate in common right now
          echo {cockatrice,common}/**/*.{cpp,h}
          echo "$(echo {cockatrice,common}/**/*.{cpp,h} | wc -w) files total"
          stats=$(lupdate {cockatrice,common}/**/*.{cpp,h} -ts cockatrice/translations/cockatrice_en@source.ts)
          echo "$stats"
          echo "::set-output name=cockatrice_stats::$stats"

      - name: Update Oracle translation source
        id: oracle
        shell: bash
        run: |
          shopt -s globstar # globstar is needed for recursive **
          lupdate -version
          echo "reading the following source files:"
          echo oracle/**/*.{cpp,h}
          echo "$(echo oracle/**/*.{cpp,h} | wc -w) files total"
          stats=$(lupdate oracle/**/*.{cpp,h} -ts oracle/translations/oracle_en@source.ts)
          echo "$stats"
          echo "::set-output name=oracle_stats::$stats"

      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update source strings ($GITHUB_SHA)
          branch: ci-source_strings
          delete-branch: true
          title: 'Update source strings'
          body: |
            After merging, all changes to the language source strings are available for translation at [Transifex](https://www.transifex.com/projects/p/cockatrice/) shortly
            - ${{ steps.cockatrice.outputs.cockatrice_stats }}
              ${{ steps.oracle.outputs.oracle_stats }}

            *This PR is automatically generated and updated via CI*
          labels: |
            CI
            Translation
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Commit: ${{ steps.create_pr.outputs.pull-request-head-sha }}"
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "Pull Request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
